# Generated by Django 6.0.1 on 2026-01-13 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('EXPENSE_USER', 'Expense User'), ('INCOME_USER', 'Income User')], default='EXPENSE_USER', max_length=20),
        ),
    ]
